Modules/Ticket/Http/routes.php
<?php
use Modules\Sap\Entities\Sap;
use Illuminate\Support\Facades\Input;
use Modules\Ticket\Http\Controllers\TicketsController;

Route::group(['middleware' => ['web','timeout'],'namespace' => 'Modules\Ticket\Http\Controllers'], function()
{
    Route::resource('tickets', 'TicketsController');
    Route::post('tickets/{ticket}',['uses'=>'TicketsController@approve','as'=>'tickets.approve']);
    Route::post('tickets/{ticket}/read',['uses'=>'TicketsController@read','as'=>'tickets.read']);
    Route::resource('replies','RepliesController');
    Route::get('sapcode','RepliesController@getSapCode')->name('sapcode');    
});

Modules/Ticket/Entities/Ticket.php
<?php

namespace Modules\Ticket\Entities;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Modules\Application\Entities\Application;
use Modules\Department\Entities\Department;
use Modules\Sap\Entities\Sap;
use Modules\Ticket\Entities\Reply;
use Modules\Ticket\Entities\TicketAttachment;

class Ticket extends Model
{

    protected $fillable = ['subject', 'body', 'sap_id', 'user_id', 'dept_id', 'ticket_type', 'integration', 'application_id', 'ticket_number', 'status'];
    protected $dates = ['submitted_hod_date', 'approved_hod_date', 'rejected_hod_date', 'submitted_dasar_date', 'approved_dasar_date', 'rejected_dasar_date', 'submitted_ptm_date', 'approved_ptm_date', 'rejected_ptm_date', 'readby_hod_date', 'readby_dasar_date', 'readby_ptm_date'];

    public function sap()
    {
        return $this->belongsTo(Sap::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function department()
    {
        return $this->belongsTo(Department::class, 'dept_id');
    }

    public function attachments()
    {
        return $this->hasMany(TicketAttachment::class);
    }

    public function application()
    {
        return $this->belongsTo(Application::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function assigned_to()
    {
        return $this->belongsTo(User::class, 'assigned_to');
    }

    // Dates Accessors
    public function getCreatedAtAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getReadbyHodDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getSubmittedHodDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getApprovedHodDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getRejectedHodDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getReadbyDasarDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getSubmittedDasarDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getApprovedDasarDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getRejectedDasarDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getReadbyPtmDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getSubmittedPtmDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getApprovedPtmDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getRejectedPtmDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }

}

Modules/Ticket/Resources/views/form.blade.php
@extends('backend.master') 
@section('content')
<div class="row">
    <div class="col-lg-6 col-md-12">
        {{-- Start Form --}} 
    @if(isset($ticket->id))
    {{-- Edit Form --}}
    <form action="{{route('tickets.update',['id'=>$ticket->id])}}" class="" method="POST" enctype="multipart/form-data">
        {{method_field('PUT')}}
    @else
    {{-- Store Form --}}
    <form action="{{route('tickets.store')}}" class="" method="POST" enctype="multipart/form-data">
    @endif
    @csrf
    <div class="card">
    @cardHeader
    {{-- Card Header --}}
    @slot('card_title')<i class="fe fe-tag"></i> {{isset($ticket) ? 'Edit Ticket':'New Ticket'}}  
    @endslot
    {{-- Card Options --}}
    <div class="card-options"> 
               
    @if(isset($ticket))
        @include('ticket::components.status')
    @endif     
    </div>
    @endcardHeader                
        @cardBody                                           
        <div class="form-group"  @if ($errors->has('subject')) has-error @endif>
                <label for="" class="form-label">Subject</label>
                <input type="hidden" name="user_id" value="{{Auth::id()}}">
               
                <input type="hidden" name="ticket_number" 
                value="{{isset($ticket) ? $ticket->ticket_number : $ticket_rn}}">               
                <input type="text" class="form-control" name="subject" value="{{old('subject',$ticket->subject ?? null)}}">
                @if ($errors->has('subject'))
                        <p class="text-danger">{{ $errors->first('subject') }}</p> 
                    @endif   
        </div>
            <div class="form-group"  @if ($errors->has('body')) has-error @endif>
                    <label for="" class="form-label">Issue</label>
            <textarea name="body" id="" cols="30" rows="5" class="form-control">{{old('body',$ticket->body ?? null)}}</textarea> 
            @if ($errors->has('body'))
                        <p class="text-danger">{{ $errors->first('body') }}</p> 
                    @endif                 
            </div>
            <div class="form-group"  @if ($errors->has('name')) has-error @endif>
                    <label for="" class="form-label">Attachments</label>
                <input type="file" class="" name="files[]" multiple>
                    @if ($errors->has('files'))
                        <p class="text-danger">{{ $errors->first('files') }}</p> 
                    @endif            
            </div>
            @if(isset($ticket))
            @if($ticket->attachments->count() > 0)
                <div class="form-group">
                    <label for="" class="form-label">Attached Files</label>
                    <div class="row gutters-sm" id="attachment">
                        @foreach($ticket->attachments as $t)             
                            <div class="col-6 col-sm-4" >
                        <a href="{{asset($t->path)}}" data-effect="mfp-move-from-top">                  
                            <img src="{{asset($t->path)}}" class="img-fluid"> 
                        </a>                
                            </div>              
                        @endforeach
                    </div>             
                </div>
            @endif
            @endif
            <div class="form-group"  @if ($errors->has('dept_id')) has-error @endif>
                    <label for="" class="form-label">Department</label>
            <select name="dept_id" id="" class="form-control selectize" placeholder="Select department">
                    @foreach($depts as $dept)                                    
                        <option value="{{$dept->id}}" 
                                @if(isset($ticket))
                                     {{$ticket->dept_id == $dept->id ? 'selected':'' }}    
                                @endif
                        >
                            {{$dept->name}}
                        </option>
                    @endforeach            
            </select>                                               
                    @if ($errors->has('dept_id'))
                    <p class="text-danger">{{ $errors->first('dept_id') }}</p> 
                    @endif            
            </div>
            <div class="form-group"  @if ($errors->has('sap_id')) has-error @endif>
                    <label for="" class="form-label">SAP Modules</label>
            <select name="sap_id" id="sap_id" class="form-control selectize">
                @foreach($sap_users as $sap)
            <option data-value="{{$sap->code}}" value="{{$sap->id}}"
                @if(isset($ticket))
                    {{$ticket->sap->id == $sap->id ? 'selected':''}}
                @endif                
                >{{$sap->name}}</option>
                @endforeach                    
            </select>                    
                    @if ($errors->has('saps'))
                    <p class="text-danger">{{ $errors->first('saps') }}</p> @endif            
            </div>
            <div class="form-group">                 
                <label for="" class="form-label">Integration with another application?</label>
                <select name="integration" id="" onchange="showDiv(this)" class="form-control selectize" placeholder="Please select">
                        <option value="">Please Select</option>
                <option value="1" {{isset($ticket) && $ticket->integration == 1 ? 'selected':''}}>Yes</option>
                        <option value="0" {{isset($ticket) && $ticket->integration == 0 ? 'selected':''}}>No</option>
                    </select>
              </div> 
             
            <div class="form-group"  @if ($errors->has('application_id')) has-error @endif>
                    <label for="" class="form-label">Applications</label>

                <select name="application_id" id="app_id" class="form-control selectize" placeholder="Select the application">
                    @foreach($apps as $app) 
                <option value="{{$app->id}}" {{isset($ticket) && $ticket->application_id == $app->id ? 'selected':''}}>{{$app->name}}</option> 
                    @endforeach 
                </select>
                @if ($errors->has('application_id'))
                        <p class="text-danger">{{ $errors->first('application_id') }}</p> 
                @endif                 
            </div>
            
            <div class="form-group"  @if ($errors->has('ticket_type')) has-error @endif>
                    <label for="" class="form-label">Ticket Type</label>
                <select name="ticket_type" id="" class="form-control selectize" onchange="showRecurring(this)">
                    <option value="new">{{ucwords('new')}}</option>
                    <option value="open">{{ucwords('open')}}</option>
                    <option value="pending">{{ucwords('pending')}}</option>
                    <option value="recurring">{{ucwords('recurring')}}</option>
                </select>
                @if ($errors->has('ticket_type'))
                        <p class="text-danger">{{ $errors->first('ticket_type') }}</p> 
                @endif 
            </div>
            <div id="old_ticket" class="form-group">
                <label for="" class="form-label">Which Ticket as recurring issue?</label>
                <select name="recurring_ticket_id" id="" class="form-control selectize">
                @foreach($user_tickets as $t)
                <option value="{{$t->id}}" {{isset($ticket) && $t->id == $ticket->recurring_ticket_id ? 'selected':''}}>#{{$t->ticket_number}} - {{$t->subject}}</option>
                @endforeach
                </select>
            </div>
            <div class="form-group"  @if ($errors->has('name')) has-error @endif>
                {{-- User can only see the buttons if ticket status == 1 (draft) --}}
                
                <button class="btn btn-md btn-primary" name="submit_hod"><i class="fe fe-send"></i> {{isset($ticket) ? 'Submit':'Submit'}}</button>
                               
                <button class="btn btn-md btn-secondary" name="draft"><i class="fe fe-save"></i> {{isset($ticket) ? 'Update Draft':'Save As Draft'}}</button>       
                
                <a href="{{route('tickets.index')}}" class="btn btn-md btn-secondary">Back</a>  
            </div>
        @endcardBody
        </div>
    </div>
    <div class="col-lg-6 col-md-12" >
            <div class="card"> 
                    @cardHeader 
                    @slot('card_title')
                    <i class="fe fe-message-circle"></i> Remarks @endslot 
                    @endcardHeader 
                    @cardBody   
                    <div class="form-group" @if ($errors->has('replybody')) has-error @endif>
                        <label for="" class="form-label">Leave a remark</label>
                    <textarea name="replybody" id="" cols="30" rows="5" class="form-control"></textarea>
                        @if ($errors->has('replybody'))
                        <p class="text-danger">{{ $errors->first('replybody') }}</p>
                        @endif
                    </div>
                    @isset($replies)
                    <div class="o-auto" style="{{$replies->count() > 3 ? 'height:17rem':''}}">
                    <ul class="list-group list-card-group">
                        @foreach($replies as $reply)
                            <li class="list-group-item py-5">
                                    <div class="media">
                                      <div class="media-object avatar avatar-md mr-4" style="background-image: url({{asset($reply->user->profile->avatar)}})"></div>
                                      <div class="media-body">
                                        <div class="media-heading">
                                                <small class="float-right text-muted">{{$reply->created_at->toDayDateTimeString()}}</small>                                          
                                          <h5>{{$reply->user->name}}</h5>                                          
                                        </div>
                                        <div>
                                          {{$reply->body}}                                          
                                        </div>
                                        
                                      </div>
                                    </div>
                                  </li>
                        @endforeach
                    </ul>
                </div>
                    @endisset  
                    @endcardBody
                </div>
    </div>
</div>
</form>
@endsection
@include('asset-partials.selectize')
@section('page-css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.css">
<style>
.mfp-move-from-top {
  /* start state */
  /* animate in */
  /* animate out */
}
.mfp-move-from-top .mfp-content {
  vertical-align: top;
}
.mfp-move-from-top .mfp-with-anim {
  opacity: 0;
  transition: all 0.2s;
  transform: translateY(-100px);
}
.mfp-move-from-top.mfp-bg {
  opacity: 0;
  transition: all 0.2s;
}
.mfp-move-from-top.mfp-ready .mfp-with-anim {
  opacity: 1;
  transform: translateY(0);
}
.mfp-move-from-top.mfp-ready.mfp-bg {
  opacity: 0.8;
}
.mfp-move-from-top.mfp-removing .mfp-with-anim {
  transform: translateY(-50px);
  opacity: 0;
}
.mfp-move-from-top.mfp-removing.mfp-bg {
  opacity: 0;
}

</style>
@endsection

@section('page-js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<script>
// Image popups
$('#attachment').magnificPopup({
  delegate: 'a',
  type: 'image',
  removalDelay: 500, //delay removal by X to allow out-animation
  callbacks: {
    beforeOpen: function() {
      // just a hack that adds mfp-anim class to markup 
       this.st.image.markup = this.st.image.markup.replace('mfp-figure', 'mfp-figure mfp-with-anim');
       this.st.mainClass = this.st.el.attr('data-effect');
    }
  }
});    
</script> 

  <script type="text/javascript">
  $(document).ready(function(){
    $('#app_id')[0].selectize.disable();
    @if(isset($ticket) && !empty($ticket->recurring_ticket_id))
        $('#old_ticket').show();
    @else
        $('#old_ticket').hide();
    @endif 

   
  });
  </script>
  <script type="text/javascript">
    function showDiv(elem){
   if(elem.value == 1){
    $('#app_id')[0].selectize.enable();
    }else{
  $('#app_id')[0].selectize.disable();
}
}
function showRecurring(elem){
    if(elem.value == 'recurring'){
        $('#old_ticket').show();
    }else{
        $('#old_ticket').hide();
    }
}
</script>
@endsection

Modules/Ticket/Resources/views/index.blade.php
@extends('backend.master') @section('content') @card @cardHeader @slot('card_title')
<i class="fe fe-tag"></i> Tickets @endslot @cardOptions
<a class="btn btn-secondary btn-sm">Total: {{ $results->count() }} {{ str_plural('Ticket', $results->count()) }}</a>

@can('add_tickets')
<a href="{{ route('tickets.create') }}" class="btn btn-primary btn-sm text-white">
    <i class=""></i> Create</a>
@endcan @endcardOptions @endcardHeader @cardBody
<div class="table-responsive">
    @table(['class'=>'table table-vcenter text-nowrap card-table table-striped', 'id'=>'datatable'])
    <thead>
        <th>#</th>
        <th>Ticket Number</th>
        <th>Subject</th>
        <th>Created By</th>
        <th>Status</th>
        <th>Created At</th>
        @can('edit_tickets', 'delete_tickets')
        <th class="text-center">Actions</th>
        @endcan
    </thead>
    <tbody>
        @foreach($results as $key => $result)
        <tr>

            <td>{{ ++$key }}</td>
            <td>{{$result->ticket_number or 'Not generated yet'}}</td>
            <td>{{ $result->subject }}</td>
            <td>{{ $result->user->name }}</td>
            <td>
                @include('ticket::components.status-index')
            </td>
            <td>{{$result->created_at}}</td>

            @can('edit_tickets')
            <td class="text-center">
                @include('ticket::layouts.index-actions')
            </td>
            @endcan

        </tr>
        @endforeach
    </tbody>
    @endtable
</div>
<div class="container">

</div>
@endcardBody @endcard @stop @include('asset-partials.datatables')

Modules/Ticket/Resources/views/reply.blade.php
<div class="card">
    @cardHeader 
    @slot('card_title')
    <i class="fe fe-message-circle"></i> Remarks @endslot 
    @endcardHeader 
    @cardBody   
    <div class="form-group" @if ($errors->has('replybody')) has-error @endif>
        <label for="" class="form-label">Leave a remark</label>
        <textarea name="replybody" id="" cols="30" rows="5" class="form-control"></textarea>
        @if ($errors->has('replybody'))
        <p class="text-danger">{{ $errors->first('replybody') }}</p>
        @endif
    </div>    
    @endcardBody
</div>

Modules/Ticket/Resources/views/show.blade.php
@extends('backend.master') @section('content') 
{{--
// Status Codes
1  = Draft - yellow
2  = Submitted to HOD - green
3  = Approved by HOD - blue
4  = Rejected by HOD - red
5  = Submitted to Dasar - green
6  = Approved by Dasar - blue
7  = Rejected by Dasar - red
8  = Submitted to PTM - green
9  = Approved by PTM - blue
10 = Rejected by PTM -red

// Buttons  
1. approve_hod = Approve by HOD
2. reject_hod  = Reject by HOD
3. approve_dasar = Approve by Dasar
4. reject_dasar = Reject by Dasar
5. approve_ptm = Approve by PTM
6. reject_ptm = Reject by PTM  
--}}

<form action="{{route('tickets.approve', ['id'=>$ticket->id])}}" method="POST">
  {{csrf_field()}}
  
  <div class="row">
        @include('ticket::layouts.progress')
  </div>    
  <div class="row">
    <div class="col-lg-6 col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            <i class="fe fe-tag"></i> 
            {{$ticket->subject}} 
            @include('ticket::components.status')
          </h3>
          <div class="card-options">
            @include('ticket::components.approve-reject-buttons')
          </div>
        </div>
        <div class="card-body">
          <table class="card-table table table-bordered">
            <tr>
              <td class="font-weight-bold">Ticket #</td>
              <td>{{$ticket->ticket_number}}</td>
            </tr>
            <tr>
              <td class="font-weight-bold">Subject</td>
              <td>{{$ticket->subject}}</td>
            </tr>
            <tr>
                <td class="font-weight-bold">Ticket Created By</td>
                <td>{{$ticket->user->name}}</td>
              </tr>
            <tr>
              <td class="font-weight-bold">Ticket Created At</td>
              <td>{{$ticket->created_at}}</td>
            </tr>
            <tr>
              <td class="font-weight-bold">Ticket Type</td>
              <td>{{ucwords($ticket->ticket_type)}}</td>
            </tr>
            <tr>
              <td class="font-weight-bold">Department</td>
              <td>{{$ticket->department->name}}</td>
            </tr>
            <tr>
              <td class="font-weight-bold">SAP Modules</td>
              <td>{{$ticket->sap->name}}</td>
            </tr>
            @if($ticket->integration == 1)
            <tr>
              <td class="font-weight-bold">App Integration?</td>
              <td>{{$ticket->integration == 1 ? 'Yes':'No'}}</td>
            </tr>
            <tr>
              <td class="font-weight-bold">App Name</td>
              <td>{{$ticket->application->name}}</td>
            </tr>
            @endif
            <tr>
              <td colspan="2" class="text-center font-weight-bold">Issue</td>
            </tr>
            <tr>
              <td colspan="2">
                {{$ticket->body}}
              </td>
            </tr>
            @if(isset($ticket)) @if($ticket->attachments->count() > 0)
            <tr>
              <td colspan="2" class="font-weight-bold">Attachments</td>
            </tr>
            <tr>
              <td colspan="2">
                <div class="row gutters-sm" id="attachment">
                  @foreach($ticket->attachments as $t)
                  <div class="col-6 col-sm-4">
                    <a href="{{asset($t->path)}}" data-toggle="lightbox" data-gallery="attachment-gallery">
                      <img src="{{asset($t->path)}}" width="200px" class="img-fluid">
                    </a>
                  </div>
                  @endforeach
                </div>
              </td>
            </tr>
            @endif @endif
          </table>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-12">
      @include('ticket::layouts.comments')
    </div>
  </div>
</form>
@endsection @include('asset-partials.selectize') @section('page-css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css">
<style>
  .card-options .btn:first-child {
    margin-right: 10px !important;
  }
  .htimeline { list-style: none; padding: 0; margin: 10px 0 0; }

.htimeline .step { float: left; border-bottom-style: solid; border-bottom-width: 5px; position: relative; margin-bottom: 10px; text-align: left; padding: 0px 0 5px 0px; background-color: #ddd; color: #333; height: 60px; vertical-align: middle; border-right: solid 1px #bbb; transition: all 0.5s ease;}
.htimeline .step:nth-child(odd) { background-color: #eee; }
.htimeline .step:first-child { border-left: solid 1px #bbb; }
.htimeline .step:hover { background-color: #ccc; border-bottom-width: 6px; }

.htimeline .step div { margin: 0 5px; font-size: 14px; vertical-align: top; padding: 0;}

.htimeline .step.green { border-bottom-color: #348F50;}
.htimeline .step.orange { border-bottom-color: #F09819;}
.htimeline .step.red { border-bottom-color: #C04848;}
.htimeline .step.blue { border-bottom-color: #49a09d;}

.htimeline .step::before { width: 15px; height: 15px; border-radius: 50px; content: ' '; background-color: white; position: absolute; bottom: -10px; left: 0px; border-style: solid; border-width: 3px; transition: all 0.5s ease;}
.htimeline .step:hover::before { width: 18px; height: 18px; bottom: -12px; }
.htimeline .step.green::before {border-color: #348F50;}
.htimeline .step.orange::before {border-color: #F09819;}
.htimeline .step.red::before {border-color: #C04848;}
.htimeline .step.blue::before {border-color: #49a09d;}

.htimeline .step::after { content: attr(data-date); position: absolute; bottom: 0px; left: 17px; font-size: 11px; font-style: italic; color: #888}
</style>
@endsection @section('page-js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>
<script>
  $(document).on('click', '[data-toggle="lightbox"]', function (event) {
    event.preventDefault();
    $(this).ekkoLightbox();
  });
</script>
@endsection