Modules/Ticket/Http/routes.php
<?php
use Modules\Sap\Entities\Sap;
use Illuminate\Support\Facades\Input;
use Modules\Ticket\Http\Controllers\TicketsController;

Route::group(['middleware' => ['web','timeout'],'namespace' => 'Modules\Ticket\Http\Controllers'], function()
{
    Route::resource('tickets', 'TicketsController');
    Route::post('tickets/{ticket}',['uses'=>'TicketsController@approve','as'=>'tickets.approve']);
    Route::post('tickets/{ticket}/read',['uses'=>'TicketsController@read','as'=>'tickets.read']);
    Route::resource('replies','RepliesController');
    Route::get('sapcode','RepliesController@getSapCode')->name('sapcode');    
});

Modules/Ticket/Entities/Ticket.php
<?php

namespace Modules\Ticket\Entities;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Modules\Application\Entities\Application;
use Modules\Department\Entities\Department;
use Modules\Sap\Entities\Sap;
use Modules\Ticket\Entities\Reply;
use Modules\Ticket\Entities\TicketAttachment;

class Ticket extends Model
{

    protected $fillable = ['subject', 'body', 'sap_id', 'user_id', 'dept_id', 'ticket_type', 'integration', 'application_id', 'ticket_number', 'status'];
    protected $dates = ['submitted_hod_date', 'approved_hod_date', 'rejected_hod_date', 'submitted_dasar_date', 'approved_dasar_date', 'rejected_dasar_date', 'submitted_ptm_date', 'approved_ptm_date', 'rejected_ptm_date', 'readby_hod_date', 'readby_dasar_date', 'readby_ptm_date'];

    public function sap()
    {
        return $this->belongsTo(Sap::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function department()
    {
        return $this->belongsTo(Department::class, 'dept_id');
    }

    public function attachments()
    {
        return $this->hasMany(TicketAttachment::class);
    }

    public function application()
    {
        return $this->belongsTo(Application::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function assigned_to()
    {
        return $this->belongsTo(User::class, 'assigned_to');
    }

    // Dates Accessors
    public function getCreatedAtAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getReadbyHodDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getSubmittedHodDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getApprovedHodDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getRejectedHodDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getReadbyDasarDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getSubmittedDasarDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getApprovedDasarDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getRejectedDasarDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getReadbyPtmDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getSubmittedPtmDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getApprovedPtmDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }
    public function getRejectedPtmDateAttribute($value)
    {
        if ($value != null) {
            return Carbon::parse($value)->toDayDateTimeString();
        }
    }

}

Modules/Ticket/Resources/views/layouts/comments.blade.php
<div class="card">
        @cardHeader @slot('card_title')
        <i class="fe fe-message-circle"></i> Comments @endslot @endcardHeader @cardBody
        <div class="form-group" @if ($errors->has('replybody')) has-error @endif>
          <label for="" class="form-label">Leave a remark</label>
          <textarea name="replybody" id="" cols="30" rows="5" class="form-control"></textarea>
          @if ($errors->has('replybody'))
          <p class="text-danger">{{ $errors->first('replybody') }}</p>
          @endif
        </div>
        @if($ticket->status == 2 || $ticket->status == 3 || $ticket->status == 4) 
        @can('add_replies')
        <div class="form-group text-right">
          <button type="submit" class="btn btn-primary btn-md" name="comment">
            <i class="fe fe-send"></i> Submit Comment</button>
        </div>
        @endcan 
        @endif 
        @isset($replies)
        <div class="o-auto" style="{{$replies->count() > 3 ? 'height:17rem':''}}">
          <ul class="list-group list-card-group">
            @foreach($replies as $reply)
            <li class="list-group-item py-5">
              <div class="media">
                <div class="media-object avatar avatar-md mr-4" style="background-image: url({{asset($reply->user->profile->avatar)}})"></div>
                <div class="media-body">
                  <div class="media-heading">
                    <small class="float-right text-muted">{{$reply->created_at->toDayDateTimeString()}}</small>
                    <h5>{{$reply->user->name}}</h5>
                  </div>
                  <br>
                  <div>
                    {{$reply->body}}
                  </div>

                </div>
              </div>
            </li>
            @endforeach
          </ul>
        </div>
        @endisset @endcardBody
      </div>

Modules/Ticket/Resources/views/layouts/index-actions.blade.php
<div class="item-action dropdown">
    <a href="javascript:void(0)" data-toggle="dropdown" class="icon">
        <button class="btn btn-sm btn-secondary">Action</button>
    </a>
    <div class="dropdown-menu dropdown-menu-right">
        @can('view_tickets')
            @if(Auth::user()->hasAnyRole(['Admin','User']))                        
                <a href="{{route('tickets.show',['id'=>$result->id])}}" class="dropdown-item"><i class="fe fe-eye"></i> View</a>
            @endif
            <form action="{{route('tickets.read', ['id'=>$result->id])}}" style="display:inline" method="POST">
                @csrf
                @role('HOD')
                <button type="submit" class="btn btn-secondary dropdown-item" name="readby_hod"><i class="fe fe-eye"></i> View</button>
                @endrole
                @role('Dasar')
                <button type="submit" class="btn btn-secondary dropdown-item" name="readby_dasar"><i class="fe fe-eye"></i> View</button>
                @endrole
                @role('PTM')
                <button type="submit" class="btn btn-secondary dropdown-item" name="readby_ptm"><i class="fe fe-eye"></i> View</button>
                @endrole
            </form>
        @endcan 
        @if($result->status == 1 || $result->status == 4) 
        @can('edit_tickets')
        <a href="{{ route('tickets.edit',['id'=>$result->id])  }}" class="dropdown-item">
            <i class="fe fe-edit"></i> Edit</a>
        @endcan 
        @endif
        
        @can('delete_tickets')
        @if($result->user_id == Auth::id())
        <div class="dropdown-divider"></div>
        {!! Form::open( ['method' => 'delete', 'url' => route('tickets.destroy', ['id'=>$result->id]), 'style'
        => 'display: inline', 'onSubmit' => 'return confirm("Are yous sure wanted to delete this ticket?")'])
        !!}
        <button type="submit" class="dropdown-item">
            <i class="fe fe-trash"></i> Delete
        </button>
        {!! Form::close() !!}
        @endif 
        @endcan
    </div>
</div>

Modules/Ticket/Resources/views/layouts/progress.blade.php
<div class="col-lg-12 col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fe fe-activity"></i> Ticket Progress</h3>
            <div class="card-options"></div>
        </div>
        <div class="card-body">
            <div class='container-fluid'>
                <div class='htimeline row'>
                    @foreach($date_arr as $d) 
                        @if($d['timestamp'] != NULL)
                <div data-date="{!! $d['timestamp'] !!}" class="step col-2 {!! $d['color']!!}">
                            <div>{!! $d['status'] !!} @if($d['code'] == $ticket->status) <i class="fe fe-check">@endif</i></div>
                        </div>
                        @endif 
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>