routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses'=>'Auth\LoginController@showLoginForm']);
// Auth
Auth::routes();
// OAuth
Route::get('login/{provider}',          'Auth\SocialAccountsController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\SocialAccountsController@handleProviderCallback');

Route::group( ['middleware' => ['auth','timeout'],'prefix'=>'backend'], function() {
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    Route::get('myprofile', 'UsersController@myprofile');
});

Route::view('mail','emails.mail');
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\LinkedSocialAccount;
use App\Profile;
use Cache;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function accounts(){
        return $this->hasMany(LinkedSocialAccount::class);
    }

    public function profile(){
        return $this->hasOne(Profile::class,'user_id');
    } 
    
    // Check if user is online

    public function isOnline()
    {
    return Cache::has('user-is-online-' . $this->id);
    }

    public function profileOwner($user){
        return $this->id == $user->id;
    }
   
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use App\Permission;
use App\Authorizable;
use App\Profile;
use App\Repositories\UsersRepository as UR;
use Auth;
use Session;
use Illuminate\Support\Facades\Storage;

class UsersController extends Controller
{
    use Authorizable;
    
    public function index(UR $repo)
    {   
        $result = $repo->allUsers();

        return view('backend.users.index', compact('result'));
    }

    public function create()
    {           
        $roles = Role::pluck('name', 'id');
        return view('backend.users.create', compact('roles'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'roles' => 'required|min:1'            
        ]);
        

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ($user = User::create($request->except('roles', 'permissions'))) {
            // sync permission
            $this->syncPermissions($request, $user);
            //departments           
            // $user->departments()->attach($request->depts);
            // user's avatar
            if ($request->hasFile('avatar')) {
                $avatar = $request->avatar;
                $avatar_new_name = $request->name. time() . $avatar->getClientOriginalName();
                $avatar->move('uploads/avatars', $avatar_new_name);
            }
            $profile = new Profile;
            $profile->user_id = $user->id;
            if(!empty($avatar_new_name)){
                $profile->avatar = 'uploads/avatars/'.$avatar_new_name;
            }else{
                $profile->avatar = 'uploads/avatars/default.svg';
            }
            $profile->hod_id = $request->hod_id;
            $profile->save();

            Session::flash('success','User has been created.');
        } else {
            Session::flash('fail','Unable to create user.');
        }        
        return redirect()->route('users.index');
    }
    

    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::pluck('name', 'id');
        $permissions = Permission::all('name', 'id');        

        return view('backend.users.edit', compact('user', 'roles', 'permissions'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,
            'roles' => 'required|min:1',
        ]);

        // Get the user
        $user = User::find($id);              
        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'));

        // check for password change
        if ($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        
        // user's avatar
        if ($request->hasFile('avatar')) {
            
            $avatar = $request->avatar;
            $avatar_new_name = $request->name. time() . $avatar->getClientOriginalName();
            $avatar->move('uploads/avatars', $avatar_new_name);
            $user->avatar->profile = 'uploads/avatars'.$avatar_new_name;
        }     
        if($request->has('hod_id')){
            $user->profile->hod_id = $request->hod_id;
            $user->profile->update();
        }  
        $user->save();
        $user->profile->update();
        // Handle the user roles
        $this->syncPermissions($request, $user);
        $user->departments()->sync($request->depts);
        $user->saps()->sync($request->saps);
        Session::flash('success','User has been updated.');
        return redirect()->back();
    }

    public function destroy($id)
    {
        if (Auth::user()->id == $id) {
            Session::flash('warning','Deletion of currently logged in user is not allowed :(')->important();
            return redirect()->back();
        }

        if (User::findOrFail($id)->delete()) {
            Session::flash('success','User has been deleted');
        } else {
            Session::flash('success','User not deleted');
        }

        return redirect()->back();
    }

    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if (!$user->hasAllRoles($roles)) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);
        return $user;
    }

    public function myprofile(){
        $user = User::find(Auth::id());
        $roles = Role::pluck('name', 'id');
        $permissions = Permission::all('name', 'id');        
        return view('backend.users.edit', compact('user', 'roles', 'permissions'));
    }
}

resources/views/backend/users/_form.blade.php
<div class="form-group @if ($errors->has('gelaran')) has-error @endif">
        {!! Form::label('gelaran', 'Gelaran') !!} {!! Form::text('gelaran', null, ['class' => 'form-control']) !!}
        @if ($errors->has('gelaran'))
        <p class="help-block">{{ $errors->first('gelaran') }}</p> @endif
    </div>
<!-- Name Form Input -->
<div class="form-group @if ($errors->has('name')) has-error @endif">
    {!! Form::label('name', 'Nama Penuh') !!} {!! Form::text('name', null, ['class' => 'form-control']) !!}
    @if ($errors->has('name'))
    <p class="help-block">{{ $errors->first('name') }}</p> @endif
</div>

<!-- email Form Input -->
<div class="form-group @if ($errors->has('email')) has-error @endif">
    {!! Form::label('email', 'E-mel') !!} {!! Form::text('email', null, ['class' => 'form-control'])
    !!} @if ($errors->has('email'))
    <p class="help-block">{{ $errors->first('email') }}</p> @endif
</div>
<!-- password Form Input -->
<div class="form-group @if ($errors->has('password')) has-error @endif">
    {!! Form::label('password', 'Kata Laluan') !!} {!! Form::password('password', ['class' => 'form-control'])
    !!} @if ($errors->has('password'))
    <p class="help-block">{{ $errors->first('password') }}</p> @endif
</div>
<div class="form-group @if ($errors->has('iclama')) has-error @endif">
    {!! Form::label('name', 'No. IC Lama (Jika Ada)') !!} {!! Form::text('iclama', null, ['class' => 'form-control']) !!}
    @if ($errors->has('iclama'))
    <p class="help-block">{{ $errors->first('iclama') }}</p> @endif
</div>
<div class="form-group @if ($errors->has('icbaru')) has-error @endif">
    {!! Form::label('name', 'No. IC Baru') !!} {!! Form::text('icbaru', null, ['class' => 'form-control']) !!}
    @if ($errors->has('icbaru'))
    <p class="help-block">{{ $errors->first('icbaru') }}</p> @endif
</div>
<div class="form-group @if ($errors->has('name')) has-error @endif">
    {!! Form::label('name', 'Tarikh Lahir') !!} {!! Form::text('dob', null, ['class' => 'form-control']) !!}
    @if ($errors->has('dob'))
    <p class="help-block">{{ $errors->first('dob') }}</p> @endif
</div>
<div class="form-group @if ($errors->has('alamat')) has-error @endif">
    {!! Form::label('alamat', 'Alamat') !!} 
    {!! Form::text('alamat1', null, ['class' => 'form-control']) !!}
    {!! Form::text('alamat2', null, ['class' => 'form-control']) !!}
    @if ($errors->has('alamat'))
    <p class="help-block">{{ $errors->first('alamat') }}</p> @endif
</div>
<div class="form-group">
<div class="form-inline">
        {!! Form::text('alamat1', null, ['class' => 'form-control mb-2 mr-sm-2','placeholder'=>'Poskod']) !!}
        {!! Form::text('alamat1', null, ['class' => 'form-control mb-2 mr-sm-2','placeholder'=>'Bandar']) !!}
        {!! Form::text('alamat1', null, ['class' => 'form-control mb-2 mr-sm-2','placeholder'=>'Negeri']) !!}
</div>
</div>
<div class="form-group @if ($errors->has('file')) has-error @endif">
        <label for="" class="">Muat Naik Salinan IC</label>
        <br>
        <input type="file">    
        @if ($errors->has('ic'))
        <p class="help-block">{{ $errors->first('ic') }}</p> 
        @endif
</div>
<div class="form-group @if ($errors->has('name')) has-error @endif">
    @if ($errors->has('name'))
    <p class="help-block">{{ $errors->first('name') }}</p> @endif
</div>
@role('Administrator')
<!-- Permissions -->
@if(isset($user)) @include('shared._permissions', ['closed' => 'true', 'model' => $user ]) @endif @endrole @include('asset-partials.selectize')

resources/views/backend/users/create.blade.php
@extends('backend.master') 
@section('content')
{!! Form::open(['route' => ['users.store'], 'files'=>true ]) !!}
<div class="row">
        <div class="col-md-4">
                <div class="card card-profile">
                  <div class="card-header" style="background-image: url({{asset('img/photos/auth-bg.jpg')}});"></div>
                  <div class="card-body text-center">
                    <img class="card-profile-img" src="{{asset('uploads/avatars/default.svg')}}" width="200px" style="background-color:#ffffff">
                    <h3 class="mb-3">Pengguna Baru</h3>                    
                    <div class="input-file-container text-center">  
                            <input class="input-file" id="my-file" type="file" name="avatar">
                            <label tabindex="0" for="my-file" class="input-file-trigger btn btn-sm btn-primary">Tukar gambar pengguna</label>
                    </div>                                                   
                  </div>
                </div>
            </div>
    <div class="col-md-8">
        @card
            @cardHeader
                @slot('card_title') Daftar Pengguna Baru @endslot
            @endcardHeader
            @cardBody
                
                    @include('backend.users._form')
                    <div class="form-group">
                            <button type="submit" class="btn btn-md btn-primary">
                                @if(isset($user->id)) Edit @else Daftar @endif
                            </button>
                            <a href="{{route('users.index')}}" class="btn btn-secondary">Back</a> 
                            </div>
            @endcardBody
        @endcard
    </div>
    </div>
    {!! Form::close() !!}
@endsection
@include('asset-partials.input-file')

resources/views/backend/users/edit.blade.php
@extends('backend.master') 
@section('content')
{!! Form::model($user, ['method' => 'PUT', 'route' => ['users.update', $user->id ],'files'=>true ]) !!}

<div class="row">
        <div class="col-md-4">
                <div class="card card-profile">
                  <div class="card-header" style="background-image: url({{asset('img/photos/auth-bg.jpg')}});"></div>
                  <div class="card-body text-center">
                    <img class="card-profile-img" src="{{asset($user->profile->avatar)}}">
                  <h3 class="mb-3">{{$user->name}}</h3>                    
                    <div class="input-file-container text-center">  
                            <input class="input-file" id="my-file" type="file" name="avatar">
                            <label tabindex="0" for="my-file" class="input-file-trigger btn btn-sm">Tukar gambar pengguna</label>
                    </div>                                        
                  </div>
                </div>
                <div class="row row-cards">
                        @role('User')
                    <div class="col">
                        <div class="card">
                                <div class="card-body p-3 text-center">                                
                                <div class="h1 m-0">{{Auth::user()->name}}</div>
                                        <div class="text-muted mb-4">Tickets Created</div>
                                      </div>
                              </div>
                            </div> 
                            @endrole                           
                </div>
                
            </div>
<div class="col-md-8">
    @card
        @cardHeader
            @slot('card_title') Edit {{ Auth::id() == $user->id ? 'Your Profile':$user->name }} @endslot
        @endcardHeader

        @cardBody              
                @include('backend.users._form')
                <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">
                            {{ isset($user->id) ? 'Update':'Create'}}
                        </button>
                        <a href="{{route('users.index')}}" class="btn btn-secondary">Back</a> 
                        </div>
                
        @endcardBody

    @endcard
</div>
</div>

{!! Form::close() !!}
@endsection
@include('asset-partials.input-file')

resources/views/backend/users/index.blade.php
@extends('backend.master') 
@section('content')
@card
    @cardHeader
        @slot('card_title')<i class="fe fe-users"></i> Senarai Ahli @endslot
        @cardOptions
        <a class="btn btn-secondary btn-sm">Jumlah: {{ $result->count() }} Ahli</a>

        @can('add_users')
        <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm text-white"> <i class=""></i> Daftar Ahli Baru</a> 
        @endcan 
        @endcardOptions
    @endcardHeader
    
    @cardBody
    <div class="table-responsive">
        @table(['class'=>'table card-table table-vcenter text-nowrap', 'id'=>'datatable'])
            <thead>
                <th>#</th>
                <th></th>
                <th>Nama</th>
                <th>E-mel</th>
                <th>Peranan</th>
                <th>Tarikh Daftar</th>
                @can('edit_users', 'delete_users')
                <th class="text-center">Tindakan</th>
                @endcan
            </thead>
            <tbody>
               @foreach($result as $key => $user)
               {{-- @if(Auth::user->hasRoles('Admin')) --}}
            <tr>
                <td>{{ ++$key }}</td>
                <td class="text-center"><div class="avatar d-block" style="background-image: url({{asset($user->profile->avatar)}})">                    
                    <span class="avatar-status {{$user->isOnline() ? 'bg-green':'bg-red'}}"></span> 
                  </div></td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->roles->implode('name', ', ') }}</td>
                <td>{{ $user->created_at->toDayDateTimeString() }}</td>
            
                @can('edit_users')
                <td class="text-center">
                    @can('edit_users')
                    <a href="{{ route('users.edit', ['id' => $user->id])  }}" class="btn btn-secondary btn-sm"><i class="fe fe-edit"></i> Edit</a>
                    @endcan
                    
                    @can('delete_users')                    
                        {!! Form::open( ['method' => 'delete', 'url' => route('users.destroy', ['id' => $user->id]), 'style' => 'display: inline', 'onSubmit' => 'return confirm("Are yous sure wanted to delete it?")']) !!}
                <button type="submit" class="btn-delete btn btn-sm btn-danger" style="visibility:{{Auth::id() == $user->id ? 'hidden':''}}">
                                <i class="fe fe-trash"></i> Padam
                            </button>
                        {!! Form::close() !!}
                    @endcan 
                </td>
                @endcan
            </tr>
            @endforeach             
            </tbody>
        @endtable
    </div>
    @endcardBody
@endcard
@include('asset-partials.datatables')
@endsection